[build]
  publish = "dist"
  command = "npm run build"

[[edge_functions]]
  function = "social-meta"
  path = "/tracks/*"

[[edge_functions]]
  function = "auth-gate"
  path = "/*"

[[edge_functions]]
  function = "test"
  path = "/test"

[build.environment]
  NODE_VERSION = "20"
