-- Seed productivity-focused audio tracks for new creators
-- Each insert is idempotent via ON CONFLICT on legacy track_id
INSERT INTO audio_tracks (
  track_id,
  title,
  url,
  audio_url,
  creator_id,
  community_id,
  category_id,
  category,
  sub_category,
  summary,
  release_date,
  full_content,
  read_time,
  main_image_url,
  main_image_caption,
  main_image_width,
  main_image_height,
  voices,
  gender,
  audio_config
) VALUES
  (
    1001,
    'Are You Hunting Antelope or Field Mice?',
    NULL,
    'https://xkwlkiweozjgujnqomze.supabase.co/storage/v1/object/public/audio-files/Tracks/2024-05-02_Tim%20Ferriss_Are%20You%20Hunting%20Antelope%20or%20Field%20Mice%3F_echo.mp3',
    (SELECT id FROM creators WHERE name = 'Tim Ferriss'),
    (SELECT id FROM communities WHERE name = 'Unknown'),
    (SELECT id FROM categories WHERE slug = 'productivity'),
    'Productivity',
    ARRAY[]::text[],
    'Tim Ferriss contrasts busywork with high-leverage hunts to focus on what truly matters.',
    '2024-05-02',
    NULL,
    '12 min listen',
    'https://images.unsplash.com/photo-1521737602349-7179cfd77f68?auto=format&fit=crop&w=1200&q=80',
    'Hunting for meaningful work',
    1200,
    630,
    '[]'::jsonb,
    'male',
    jsonb_build_object(
      'voice_preference', 'echo',
      'tone_override', 'Deliver with the calm urgency associated with Tim Ferriss'
    )
  ),
  (
    1002,
    'For Less Anxiety and More Life, Treat Your To-Do List Like a Diner Menu',
    NULL,
    'https://xkwlkiweozjgujnqomze.supabase.co/storage/v1/object/public/audio-files/Tracks/2025-02-25_Tim%20Ferriss_For%20Less%20Anxiety%20and%20More%20Life%2C%20Treat%20Your%20To-Do%20List%20Like%20a%20Diner%20Menu_echo.mp3',
    (SELECT id FROM creators WHERE name = 'Tim Ferriss'),
    (SELECT id FROM communities WHERE name = 'Unknown'),
    (SELECT id FROM categories WHERE slug = 'productivity'),
    'Productivity',
    ARRAY[]::text[],
    'A mental model from Tim Ferriss for batching priorities so your schedule serves you, not the other way around.',
    '2025-02-25',
    NULL,
    '11 min listen',
    'https://images.unsplash.com/photo-1521737602349-7179cfd77f68?auto=format&fit=crop&w=1200&q=80',
    'Menu-style planning',
    1200,
    630,
    '[]'::jsonb,
    'male',
    jsonb_build_object(
      'voice_preference', 'echo',
      'tone_override', 'Keep narration approachable while reinforcing calm execution'
    )
  ),
  (
    1003,
    'When the 80/20 Rule Fails: The Downside of Being Effective',
    NULL,
    'https://xkwlkiweozjgujnqomze.supabase.co/storage/v1/object/public/audio-files/Tracks/2018-10-08_James%20Clear_When%20the%208020%20Rule%20Fails-The%20Downside%20of%20Being%20Effective_alloy.mp3',
    (SELECT id FROM creators WHERE name = 'James Clear'),
    (SELECT id FROM communities WHERE name = 'Unknown'),
    (SELECT id FROM categories WHERE slug = 'productivity'),
    'Productivity',
    ARRAY[]::text[],
    'James Clear explains why being highly efficient can backfire without clear boundaries.',
    '2018-10-08',
    NULL,
    '9 min listen',
    'https://images.unsplash.com/photo-1553877522-43269d4ea984?auto=format&fit=crop&w=1200&q=80',
    'The cost of effectiveness',
    1200,
    630,
    '[]'::jsonb,
    'male',
    jsonb_build_object(
      'voice_preference', 'alloy',
      'tone_override', 'Sound analytical and reflective to match James Clear’s writing style'
    )
  ),
  (
    1004,
    'The Surprising Benefits of Journaling One Sentence Every Day',
    NULL,
    'https://xkwlkiweozjgujnqomze.supabase.co/storage/v1/object/public/audio-files/Tracks/2019-01-07_James%20Clear_The%20Surprising%20Benefits%20of%20Journaling%20One%20Sentence%20Every%20Day_alloy.mp3',
    (SELECT id FROM creators WHERE name = 'James Clear'),
    (SELECT id FROM communities WHERE name = 'Unknown'),
    (SELECT id FROM categories WHERE slug = 'productivity'),
    'Productivity',
    ARRAY[]::text[],
    'James Clear shows how a tiny daily journaling habit compounds into lasting clarity.',
    '2019-01-07',
    NULL,
    '8 min listen',
    'https://images.unsplash.com/photo-1515378791036-0648a3ef77b2?auto=format&fit=crop&w=1200&q=80',
    'Micro journaling habit',
    1200,
    630,
    '[]'::jsonb,
    'male',
    jsonb_build_object(
      'voice_preference', 'alloy',
      'tone_override', 'Keep delivery clear and encouraging for habit formation'
    )
  ),
  (
    1005,
    'How Experts Figure Out What to Focus On',
    NULL,
    'https://xkwlkiweozjgujnqomze.supabase.co/storage/v1/object/public/audio-files/Tracks/2015-08-14_James%20Clear_How%20Experts%20Figure%20What%20to%20Focus%20On_alloy.mp3',
    (SELECT id FROM creators WHERE name = 'James Clear'),
    (SELECT id FROM communities WHERE name = 'Unknown'),
    (SELECT id FROM categories WHERE slug = 'productivity'),
    'Productivity',
    ARRAY[]::text[],
    'Frameworks from James Clear for narrowing your attention to the work that matters most.',
    '2015-08-14',
    NULL,
    '10 min listen',
    'https://images.unsplash.com/photo-1512757776214-26d36777b513?auto=format&fit=crop&w=1200&q=80',
    'Focus frameworks',
    1200,
    630,
    '[]'::jsonb,
    'male',
    jsonb_build_object(
      'voice_preference', 'alloy',
      'tone_override', 'Guide the listener through deliberate, thoughtful pacing'
    )
  ),
  (
    1006,
    'The Ultimate Productivity Hack Is Saying No',
    NULL,
    'https://xkwlkiweozjgujnqomze.supabase.co/storage/v1/object/public/audio-files/Tracks/2019-03-26_James%20Clear_The%20Ultimate%20Productivity%20Hack%20Is%20Saying%20No_alloy.mp3',
    (SELECT id FROM creators WHERE name = 'James Clear'),
    (SELECT id FROM communities WHERE name = 'Unknown'),
    (SELECT id FROM categories WHERE slug = 'productivity'),
    'Productivity',
    ARRAY[]::text[],
    'James Clear argues that intentional refusal is the highest form of focus.',
    '2019-03-26',
    NULL,
    '7 min listen',
    'https://images.unsplash.com/photo-1480694313141-fce5e697ee25?auto=format&fit=crop&w=1200&q=80',
    'Protecting focus',
    1200,
    630,
    '[]'::jsonb,
    'male',
    jsonb_build_object(
      'voice_preference', 'alloy',
      'tone_override', 'Deliver with confident restraint to reinforce boundary setting'
    )
  ),
  (
    1007,
    'For a More Creative Brain, Follow These 5 Steps',
    NULL,
    'https://xkwlkiweozjgujnqomze.supabase.co/storage/v1/object/public/audio-files/Tracks/2016-07-25_James%20CLear_For%20A%20More%20Creative%20Brain%20Follow%20These%205%20Steps_alloy.mp3',
    (SELECT id FROM creators WHERE name = 'James Clear'),
    (SELECT id FROM communities WHERE name = 'Unknown'),
    (SELECT id FROM categories WHERE slug = 'productivity'),
    'Productivity',
    ARRAY[]::text[],
    'A James Clear playbook for priming creativity through repeatable cues.',
    '2016-07-25',
    NULL,
    '9 min listen',
    'https://images.unsplash.com/photo-1487014679447-9f8336841d58?auto=format&fit=crop&w=1200&q=80',
    'Creative rituals',
    1200,
    630,
    '[]'::jsonb,
    'male',
    jsonb_build_object(
      'voice_preference', 'alloy',
      'tone_override', 'Balance curiosity with structure to mirror James Clear’s tone'
    )
  ),
  (
    1008,
    'How Procrastination Affects Your Daily Life',
    NULL,
    'https://xkwlkiweozjgujnqomze.supabase.co/storage/v1/object/public/audio-files/Tracks/2025-01-21_Ali%20Abdaal_How%20procrastination%20affects%20your%20daily%20life_echo.mp3',
    (SELECT id FROM creators WHERE name = 'Ali Abdaal'),
    (SELECT id FROM communities WHERE name = 'Unknown'),
    (SELECT id FROM categories WHERE slug = 'productivity'),
    'Productivity',
    ARRAY[]::text[],
    'Ali Abdaal breaks down the hidden cost of delaying deep work and how to reset.',
    '2025-01-21',
    NULL,
    '10 min listen',
    'https://images.unsplash.com/photo-1521737602349-7179cfd77f68?auto=format&fit=crop&w=1200&q=80',
    'Facing procrastination',
    1200,
    630,
    '[]'::jsonb,
    'male',
    jsonb_build_object(
      'voice_preference', 'echo',
      'tone_override', 'Keep the pace upbeat and practical like Ali Abdaal’s delivery'
    )
  ),
  (
    1009,
    'How to Build a Time Management Routine',
    NULL,
    'https://xkwlkiweozjgujnqomze.supabase.co/storage/v1/object/public/audio-files/Tracks/2025-01-29_Ali%20Abdaal_How%20to%20build%20a%20time%20management%20routine_alloy.mp3',
    (SELECT id FROM creators WHERE name = 'Ali Abdaal'),
    (SELECT id FROM communities WHERE name = 'Unknown'),
    (SELECT id FROM categories WHERE slug = 'productivity'),
    'Productivity',
    ARRAY[]::text[],
    'Ali Abdaal outlines a step-by-step routine for structuring energy and attention.',
    '2025-01-29',
    NULL,
    '9 min listen',
    'https://images.unsplash.com/photo-1512757776214-26d36777b513?auto=format&fit=crop&w=1200&q=80',
    'Routinized planning',
    1200,
    630,
    '[]'::jsonb,
    'male',
    jsonb_build_object(
      'voice_preference', 'alloy',
      'tone_override', 'Blend enthusiasm with clarity for actionable instruction'
    )
  ),
  (
    1010,
    'How to Never Be Bored at Work',
    NULL,
    'https://xkwlkiweozjgujnqomze.supabase.co/storage/v1/object/public/audio-files/Tracks/2025-02-05_Ali%20Abdaal_How%20To%20Never%20Be%20Bored%20At%20Work_nova.mp3',
    (SELECT id FROM creators WHERE name = 'Ali Abdaal'),
    (SELECT id FROM communities WHERE name = 'Unknown'),
    (SELECT id FROM categories WHERE slug = 'productivity'),
    'Productivity',
    ARRAY[]::text[],
    'Ali Abdaal explores curiosity-driven experiments to keep work engaging.',
    '2025-02-05',
    NULL,
    '8 min listen',
    'https://images.unsplash.com/photo-1481487196290-c152efe083f5?auto=format&fit=crop&w=1200&q=80',
    'Staying engaged',
    1200,
    630,
    '[]'::jsonb,
    'male',
    jsonb_build_object(
      'voice_preference', 'nova',
      'tone_override', 'Sound curious and inspiring while remaining grounded'
    )
  )
ON CONFLICT (track_id) DO UPDATE SET
  title = EXCLUDED.title,
  url = EXCLUDED.url,
  audio_url = EXCLUDED.audio_url,
  creator_id = EXCLUDED.creator_id,
  community_id = EXCLUDED.community_id,
  category_id = EXCLUDED.category_id,
  category = EXCLUDED.category,
  sub_category = EXCLUDED.sub_category,
  summary = EXCLUDED.summary,
  release_date = EXCLUDED.release_date,
  full_content = EXCLUDED.full_content,
  read_time = EXCLUDED.read_time,
  main_image_url = EXCLUDED.main_image_url,
  main_image_caption = EXCLUDED.main_image_caption,
  main_image_width = EXCLUDED.main_image_width,
  main_image_height = EXCLUDED.main_image_height,
  voices = EXCLUDED.voices,
  gender = EXCLUDED.gender,
  audio_config = EXCLUDED.audio_config;
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM pg_proc WHERE proname = 'update_category_counts'
  ) THEN
    PERFORM update_category_counts();
  END IF;
END $$;
